server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/bookdb
    username: bookuser
    password: fizzingwhizbee
    driverClassName: org.postgresql.Driver
  flyway:
    enabled: true



